### ISSUE TITLE
Runtime Issue : java.lang.RuntimeException: io.grpc.StatusRuntimeException: INVALID_ARG UMENT: invalid WriteRelationshipsRequest.Updates[0]: 

### ISSUE THREAD

**Issue by kohli-rahul** [quarkiverse/quarkus-authzed-client#5]
When I am trying to load the schema and tuples using

>quarkus.authzed.devservices.schema-location=filesystem:C:\\Users\\rahul.kohli\\projects\\procurement\\src\\main\\resources\\spicedb-model.txt
>quarkus.authzed.devservices.authorization-tuples-location=filesystem:C:\\Users\\rahul.kohli\\projects\\procurement\\src\\main\\resources\\spicedb-relations.txt

getting the below error. I have also attached the file that I am trying to load.

```
ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor#startContainers threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: io.grpc.StatusRuntimeException: INVALID_ARG
        UMENT: invalid WriteRelationshipsRequest.Updates[0]: embedded message failed validation | caused by: invalid RelationshipUpdate.Relationship: embedded message failed validation | caused by: invalid Relationship.Subject: embedded mes
        sage failed validation | caused by: invalid SubjectReference.Object: embedded message failed validation | caused by: invalid ObjectReference.ObjectId: value does not match regex pattern "^(([a-zA-Z0-9_][a-zA-Z0-9/_|-]{0,127})|\\*)$"
                at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.startContainers(DevServicesAuthzedProcessor.java:134)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.Enha
[spicedb-model.txt](https://github.com/quarkiverse/quarkus-authzed-client/files/9633478/spicedb-model.txt)
[spicedb-relations.txt](https://github.com/quarkiverse/quarkus-authzed-client/files/9633479/spicedb-relations.txt)
ncedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
                at java.base/java.lang.Thread.run(Thread.java:833)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: java.lang.RuntimeException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid WriteRelationshipsRequest.Updates[0]: embedded message failed validation | caused by: invalid RelationshipUpdate.Relationship: embedded
         message failed validation | caused by: invalid Relationship.Subject: embedded message failed validation | caused by: invalid SubjectReference.Object: embedded message failed validation | caused by: invalid ObjectReference.ObjectId:
         value does not match regex pattern "^(([a-zA-Z0-9_][a-zA-Z0-9/_|-]{0,127})|\\*)$"
                at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.withClient(DevServicesAuthzedProcessor.java:334)
                at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.lambda$startContainer$5(DevServicesAuthzedProcessor.java:197)
                at java.base/java.util.Optional.orElseGet(Optional.java:364)
                at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.startContainer(DevServicesAuthzedProcessor.java:253)
                at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.startContainers(DevServicesAuthzedProcessor.java:112)
                ... 11 more
        Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid WriteRelationshipsRequest.Updates[0]: embedded message failed validation | caused by: invalid RelationshipUpdate.Relationship: embedded message failed validation |
         caused by: invalid Relationship.Subject: embedded message failed validation | caused by: invalid SubjectReference.Object: embedded message failed validation | caused by: invalid ObjectReference.ObjectId: value does not match regex 
        pattern "^(([a-zA-Z0-9_][a-zA-Z0-9/_|-]{0,127})|\\*)$"
                at io.grpc.Status.asRuntimeException(Status.java:535)
                at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
                at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
                at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
                at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
                at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
                at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)

```

[spicedb-relations.txt](https://github.com/quarkiverse/quarkus-authzed-client/files/9633552/spicedb-relations.txt)
[spicedb-model.txt](https://github.com/quarkiverse/quarkus-authzed-client/files/9633553/spicedb-model.txt)

**Comment by iocanel** [comment]
This seesm to be fixed in 0.0.3.
