### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: Unable to load  authorization model

### ISSUE THREAD

**Issue by kohli-rahul** [quarkiverse/quarkus-authzed-client#6]
When I use the below config in application-property file.

> quarkus.authzed.devservices.schema-location=classpath:spicedb-model.txt
> quarkus.authzed.devservices.authorization-tuples-location=classpath:spicedb-relations.txt   

Getting the below error
```

   ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
              [error]: Build step io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor#startContainers threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to load 
      authorization model from 'classpath:spicedb-model.txt'
              at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.startContainers(DevServicesAuthzedProcessor.java:134)
              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
              at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
              at java.base/java.lang.reflect.Method.invoke(Method.java:568)
              at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:977)
              at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
              at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
              at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
              at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
              at java.base/java.lang.Thread.run(Thread.java:833)
              at org.jboss.threads.JBossThread.run(JBossThread.java:501)
      Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to load authorization model from 'classpath:spicedb-model.txt'
              at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.withClient(DevServicesAuthzedProcessor.java:334)
              at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.lambda$startContainer$5(DevServicesAuthzedProcessor.java:197)
              at java.base/java.util.Optional.orElseGet(Optional.java:364)
              at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.startContainer(DevServicesAuthzedProcessor.java:253)
              at io.quarkiverse.authzed.client.deployment.DevServicesAuthzedProcessor.startContainers(DevServicesAuthzedProcessor.java:112)
              ... 11 more

```
File Location

> resources/spicedb-model.txt
> resources/spicedb-relations.txt

[spicedb-model.txt](https://github.com/quarkiverse/quarkus-authzed-client/files/9633531/spicedb-model.txt)
[spicedb-relations.txt](https://github.com/quarkiverse/quarkus-authzed-client/files/9633532/spicedb-relations.txt)

**Comment by iocanel** [comment]
As of #8 I can no longer reproduce.
